# pyvips supports cffi ABI and API mode
#
# During setup.py, it will attempt to compile a generated wrapper against the
# libvips headers -- this is why it needs pkgconfig and libvips in host.
#
# At runtime, it will first try to load the compiled wrapper, and if that
# fails, will fall back to ABI mode, ie. directly opening the libvips shared
# library and calling into it with cffi.

{% set name = "pyvips" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libvips/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1ab3c901fb9ae2221eef4b2258cddbaf52af30fc6d6023d610ebbe7cd94d3aff

build:
  number: 1
  script_env:
    # Switch default pkg-config implementation to pkgconf
    # https://github.com/conda-forge/conda-forge.github.io/issues/1880
    - PKG_CONFIG=pkgconf
  script:
    # Allow pkg-config to find xproto.pc
    - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PREFIX/share/pkgconfig"  # [linux]
    # Ensure we can find the vips package
    - pkgconf --exists --print-errors vips
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  ignore_run_exports:
    # We need to pull in metapackages for these below to get devel files, but
    # don't depend on these libraries directly:
    - libexpat

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkgconf
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cffi >=1.0                          # [build_platform != target_platform]
    - pkgconfig >=1.5                     # [build_platform != target_platform]
    - libvips                             # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=61
    - cffi >=1.0
    # Needed for devel files (e.g. pkg-config):
    - expat
    - freetype
    - glib
    - libvips
    - libxml2-devel
    - pkgconfig >=1.5
    # needed to find OpenSlide on Linux
    # https://github.com/conda-forge/xorg-libx11-feedstock/issues/51
    - xorg-xorgproto                      # [linux]
  run:
    - python
    - cffi >=1.0

test:
  requires:
    - pip
  imports:
    - pyvips
    - _libvips
  commands:
    - pip check
    - python -c "import pyvips; assert pyvips.API_mode"

about:
  home: https://github.com/libvips/pyvips
  dev_url: https://github.com/libvips/pyvips
  doc_url: https://libvips.github.io/pyvips
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Binding for libvips

extra:
  recipe-maintainers:
    - jcupitt
    - hmaarrfk
    - kleisauke
